#ifndef PROJECT_H__
#define PROJECT_H__

#define FLASH_ADDR0_LAT		LATC
#define FLASH_ADDR0_TRIS	TRISC
#define FLASH_ADDR1_LAT		LATD
#define FLASH_ADDR1_TRIS	TRISD
#define FLASH_ADDR2_LAT		LATE
#define FLASH_ADDR2_TRIS	TRISE
#define FLASH_ADDR2_TRISbits	TRISEbits

#define FLASH_DATA		PORTA
#define FLASH_DATA_LAT	LATA
#define FLASH_DATA_TRIS	TRISA

#define FLASH__OE_LAT	LATBbits.LATB0
#define FLASH__OE_TRIS	TRISBbits.TRISB0
#define FLASH__WE_LAT	LATBbits.LATB1
#define FLASH__WE_TRIS	TRISBbits.TRISB1
#define FLASH__CE_LAT	LATBbits.LATB2
#define FLASH__CE_TRIS	TRISBbits.TRISB2

#define SWITCH_TRIS		TRISBbits.TRISB4
#define SWITCH_PORT		PORTBbits.RB4

#define ROM__OE_TRIS	TRISBbits.TRISB3
#define ROM__OE_LAT		LATBbits.LATB3

#endif
